// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFXTdAxdX15AYcwc4Vq4AzX4gk6o7XJvs',
    appId: '1:18542948144:web:1d620ab2fc1380368ee2f5',
    messagingSenderId: '18542948144',
    projectId: 'preparation-guru',
    authDomain: 'preparation-guru.firebaseapp.com',
    storageBucket: 'preparation-guru.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzTY66aCK2I-oAHdtGnB6yzvybuYIgtk',
    appId: '1:18542948144:android:b3d8e68bdb50c17f8ee2f5',
    messagingSenderId: '18542948144',
    projectId: 'preparation-guru',
    storageBucket: 'preparation-guru.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc_0OnAJhy87VVmELQ8pv6sSua_raHAoI',
    appId: '1:18542948144:ios:d44128f6a72c56ab8ee2f5',
    messagingSenderId: '18542948144',
    projectId: 'preparation-guru',
    storageBucket: 'preparation-guru.appspot.com',
    iosBundleId: 'com.sofolit.preparationGuru',
  );
}
